name: collection_app
description: File collection manager app, initially for images, but could expand to other file types.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.2+2

environment:
  sdk: "^3.9.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  from_zero_ui:
    # TODO: 1 import from_zero_ui from a proper github link, with version tag.
    path: ../from_zero_ui/

  # * Language Extensions
  intl: ^0.20.2
  dartx: ^1.2.0

  # * State Management
  go_router: 10.0.0 # from_zero is tied to this version, it will be a lot of work to update this because our routing solution is tightly coupled to it
  flutter_riverpod: 2.0.0-dev.9 # can't update until cacheTime is re-added, lots of potential bugs to be fixed with this update, when updating, also try https://pub.dev/packages/riverpod_lint and https://pub.dev/packages/riverpod_generator
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.4.2

  # * Widgets / UI
  flutter_font_icons: ^2.2.7
  animations: ^2.0.11
  auto_size_text: ^3.0.0
  sliver_tools: ^0.2.12
  flutter_staggered_grid_view: ^0.7.0

  # * Plugins
  url_launcher: ^6.3.1
  bitsdojo_window: ^0.1.6 # ideally, we would do all window-related stuff with window_manager, and remove this dependency here
  window_manager: ^0.4.3
  video_player_win: 2.3.10 # TODO: 1 can we replace this with a multi-platform solution?
  resolve_windows_shortcut: ^2.0.0

  # * Specific Utility
  dio: ^5.8.0+1
  dio_smart_retry: ^7.0.1
  uuid: ^4.5.2
  # TODO: 2 migrate to the new dart logging solution?
  mlog:
    version: ^1.0.1
    git:
      url: https://github.com/ross96D/mlog
      tag_pattern: "{{version}}"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0
  restrict_imports_linter:
    # TODO: 1 import this from git properly
    path: ../restrict_imports_linter/
  flutter_launcher_icons: ^0.14.3 # to run:  flutter pub run flutter_launcher_icons:main
  flutter_native_splash: ^2.4.6 # to run:  flutter pub run flutter_native_splash:create
  sqflite_common_ffi: ^2.4.0


dependency_overrides:
  intl: ^0.20.2    # apparently packages before 1.0 break on every minor version, which makes it pretty much unusable
  archive: ^4.0.7  # old excel fork forces 3.3.7 which has security issues, we should if features implemented by us are already available in excel package and migrate


flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "logo.png"

flutter_native_splash:
  color: "#000064"
  #  color_dark: "#121212"
  image: "assets/images/mpg_cuba_inverse.png"
  android: true
  web: true
  ios: true
